// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK4tr7m5hPFES68xhyR-z7jbY9qH5-CLM',
    appId: '1:1081640870550:web:c500b81cd327f7fffe18b7',
    messagingSenderId: '1081640870550',
    projectId: 'workoutapp-b1ff8',
    authDomain: 'workoutapp-b1ff8.firebaseapp.com',
    storageBucket: 'workoutapp-b1ff8.firebasestorage.app',
    measurementId: 'G-DW9M1R7QN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPU1TYFff91ueZGP4SXb6DfrO6j79tEvs',
    appId: '1:1081640870550:android:9af31413ad81102efe18b7',
    messagingSenderId: '1081640870550',
    projectId: 'workoutapp-b1ff8',
    storageBucket: 'workoutapp-b1ff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfGlcidFKZrGvXKGPT9qwp-w7ugdryha8',
    appId: '1:1081640870550:ios:f784cf72719858bcfe18b7',
    messagingSenderId: '1081640870550',
    projectId: 'workoutapp-b1ff8',
    storageBucket: 'workoutapp-b1ff8.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfGlcidFKZrGvXKGPT9qwp-w7ugdryha8',
    appId: '1:1081640870550:ios:f784cf72719858bcfe18b7',
    messagingSenderId: '1081640870550',
    projectId: 'workoutapp-b1ff8',
    storageBucket: 'workoutapp-b1ff8.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK4tr7m5hPFES68xhyR-z7jbY9qH5-CLM',
    appId: '1:1081640870550:web:98b702ef247292ecfe18b7',
    messagingSenderId: '1081640870550',
    projectId: 'workoutapp-b1ff8',
    authDomain: 'workoutapp-b1ff8.firebaseapp.com',
    storageBucket: 'workoutapp-b1ff8.firebasestorage.app',
    measurementId: 'G-NEECD47VDV',
  );
}
